#!/usr/bin/env python3
import json
import pathlib
import re
import subprocess
import sys

SHIPPED_TARGETS = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "aarch64-linux-android",
    "x86_64-linux-android",
]
COVERED_BY_QUICHE_LICENCE = {"quiche", "octets"}
PREFERRED_LICENCES = ["MIT", "BSD-3-Clause", "BSD-2-Clause", "Apache-2.0"]
LICENCE_FILES = {
    "MIT": ["LICENSE-MIT", "LICENSE-MIT.txt", "LICENSE-MIT.md", "LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING"],
    "BSD-3-Clause": ["LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING"],
    "BSD-2-Clause": ["LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING"],
    "Apache-2.0": ["LICENSE-APACHE", "LICENSE-APACHE.txt", "LICENSE", "LICENSE.txt"],
}
EXTRA_NOTICE_FILES = ["NOTICE", "NOTICE.txt", "NOTICE.md"]
RULE = "=" * 78


def cargo(source, *args):
    return subprocess.run(["cargo", *args], cwd=source, check=True, capture_output=True, text=True).stdout


def linked_crates(source):
    target_args = [arg for target in SHIPPED_TARGETS for arg in ("--target", target)]
    tree = cargo(source, "tree", "-e", "normal,no-proc-macro", "-p", "quiche", "--features", "ffi",
                 "--prefix", "none", "--locked", "--format", "{p}", *target_args)
    crates = set()
    for line in tree.splitlines():
        match = re.match(r"^(\S+) v(\S+)", line.strip())
        if match:
            crates.add((match.group(1), match.group(2)))
    return crates


def chosen_licence(expression):
    alternatives = {part.strip() for part in re.split(r"\s+OR\s+|/", expression)}
    for licence in PREFERRED_LICENCES:
        if licence in alternatives:
            return licence
    sys.exit(f"rust-crate-notices.py: no known licence to use from '{expression}' - add it to PREFERRED_LICENCES.")


def licence_text(crate_dir, name, licence):
    for candidate in LICENCE_FILES[licence]:
        path = crate_dir / candidate
        if path.is_file():
            return path.read_text(encoding="utf-8").strip()
    sys.exit(f"rust-crate-notices.py: {name} ships no {licence} licence file in {crate_dir} - "
             "its notice has to be written by hand before it can be distributed.")


def notices_of(crate_dir):
    return [(crate_dir / name).read_text(encoding="utf-8").strip()
            for name in EXTRA_NOTICE_FILES if (crate_dir / name).is_file()]


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: rust-crate-notices.py <quiche source dir> > licenses/rust-crates.txt")
    source = pathlib.Path(sys.argv[1])
    metadata = json.loads(cargo(source, "metadata", "--format-version", "1", "--locked"))
    packages = {(p["name"], p["version"]): p for p in metadata["packages"]}
    sections = []
    for name, version in sorted(linked_crates(source)):
        if name in COVERED_BY_QUICHE_LICENCE:
            continue
        package = packages[(name, version)]
        expression = package.get("license") or ""
        licence = chosen_licence(expression)
        crate_dir = pathlib.Path(package["manifest_path"]).parent
        body = [licence_text(crate_dir, name, licence), *notices_of(crate_dir)]
        header = f"{name} {version}\nLicence: {expression} (distributed under {licence})"
        sections.append(f"{RULE}\n{header}\n{RULE}\n\n" + "\n\n".join(body) + "\n")
    print("Rust crates statically linked into Deskhub through quiche (quiche and octets\n"
          "themselves: see BSD-2-Clause-quiche.txt; the Apache-2.0 text: see Apache-2.0.txt).\n"
          "Generated by scripts/rust-crate-notices.py from third_party/quiche/src.\n")
    print("\n".join(sections), end="")


main()
