name: build-mobile

on:
  workflow_call:

permissions:
  contents: read

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/android-sdk
        with:
          gradle: 'true'

      - uses: ./.github/actions/third-party
        with:
          targets: android
          cache-key: android

      - name: Build debug APK (make build-android)
        run: make build-android

      - name: Upload apk
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: deskhub-android
          path: client/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 14
          if-no-files-found: error

  ios:
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/third-party
        with:
          targets: aarch64-apple-ios-sim aarch64-apple-ios
          cache-key: ios-app

      - name: Build iOS app for Simulator (make build-ios)
        run: make build-ios
